name: CI Build

on:
  workflow_dispatch:
  push:
    #    branches: [ main, 5.0.x, 4.5.x, 'issue/**' ]
    branches: [ 'issue/actions' ]

permissions: read-all

jobs:
  build-java:
    strategy:
      matrix:
        java-version: [ base, main ]
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-release/actions/setup-maven@main
        with:
          java-version: ${{ matrix.java-version }}
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Mongo Version
        id: determine-mongo-version
        uses: spring-projects/spring-data-mongodb/.github/actions/managed-version@issue/actions
        with:
          managed-versions: ${CONFIG_JSON}
          key: '.database.mongodb'
          version: 'latest'
      - name: Start MongoDB
        uses: spring-projects/spring-data-mongodb/.github/actions/start-mongodb-server@issue/actions
        with:
          mongo-version: ${{ steps.determine-mongo-version.outputs.managed-version }}
      - name: Build
        uses: spring-projects/spring-data-release/actions/maven-build@main
        with:
          additional-options: '-Pit'
